### ISSUE TITLE
[Question] Any idea of the progress 

### ISSUE THREAD

**Issue by shug0** [ThomasTerp/jc3mp-inventory#1]
Hi Thomas, I will need to use a inventory mod for my custom server. Your mod seems pretty cool and can save me a lot of time 😃 . 

Do you have a idea of the estimate progress time remaining ? 
Maybe I can help you to finish in other case 🤔

Best regards,

**Comment by ThomasTerp** [comment]
It's hard to say how long it will take, might be a few weeks, maybe more, maybe less. I'm creating it for a survival server, however I will put the inventory up for download on the forum once its done.
I prefer to work alone on my projects, but there might be some things you can help with.

**Comment by shug0** [comment]
Okay, I will build a minimal one I think :) Thanks I will keep a eye on the project !
